### ISSUE TITLE
Column names not upper case

### ISSUE THREAD

**Issue by frankvdh** [smart-flex/DbfEngine#1]
Hi Galisha,
Thanks for sharing. I tried using your library to read a .dbf that included as part of a "Shapefile". This .dbf has column names which are all lowercase, so your program fails. :(

Removing the .toUpperCase() in lines 257, 259, 269 of DbfRecord.java means it works. :)

**Comment by galisha** [comment]
Hi frankvdh,

Thanks for issue and sorry for delay. 
Traditionally DBF columns are all in upper case. I added fix in Dbf column parse method and one special test for that case. All of them will be available in 1.10 version

**Comment by galisha** [comment]
Realized in 1.10 version
