### ISSUE TITLE
Buffer reads are not stream-safe

### ISSUE THREAD

**Issue by frankvdh** [smart-flex/DbfEngine#2]
Reading the DBF header from the input stream assumes that all bytes are read. Whilst this works fine for files, it is not true for network streams

**Comment by galisha** [comment]
Hi frankvdh,

Thanks for issue and sorry for delay.
This bug fixed and under testing now.  I am going to release 1.10 version after 18-JAN. If you want get jar file early then send me private letter 
(I did not find email in your's profile).

**Comment by galisha** [comment]
Fixed in 1.10 version
